@extends('layouts.app')
@section('title', 'A.S ZINGA — La passion du football, l’avenir de nos jeunes')
@section('content')
<section class="relative overflow-hidden bg-zinc-950 text-white">
 <div class="absolute inset-0 bg-[radial-gradient(circle_at_75%_25%,rgba(249,115,22,.22),transparent_35%)]"></div>
 <div class="relative mx-auto grid min-h-[720px] max-w-7xl items-center gap-12 px-4 py-20 lg:grid-cols-[1.1fr_.9fr] lg:px-8">
  <div><span class="inline-flex rounded-full border border-orange-400/40 bg-orange-500/10 px-4 py-2 text-xs font-black uppercase tracking-[.22em] text-orange-400">Abobo • Abidjan • Côte d’Ivoire</span><h1 class="mt-7 max-w-4xl text-5xl font-black leading-[.92] tracking-tight sm:text-7xl lg:text-8xl">PLUS QU’UN CLUB.<br><span class="text-orange-500">UN AVENIR.</span></h1><p class="mt-7 max-w-2xl text-lg leading-8 text-zinc-300">A.S ZINGA accompagne la jeunesse par le football, la discipline, le travail et l’esprit collectif. Ici, chaque entraînement prépare un joueur, mais aussi un homme.</p><div class="mt-9 flex flex-wrap gap-3"><a href="{{ route('matches') }}" class="rounded-full bg-orange-500 px-7 py-3.5 font-black text-white transition hover:bg-orange-400">Voir nos matchs</a><a href="{{ route('team') }}" class="rounded-full border border-white/25 px-7 py-3.5 font-black transition hover:bg-white hover:text-zinc-950">Découvrir l’équipe</a></div>
  <div class="mt-10 flex gap-8 border-t border-white/10 pt-7 text-sm text-zinc-400"><div><strong class="block text-2xl text-white">Abobo</strong>Notre territoire</div><div><strong class="block text-2xl text-white">Jeunesse</strong>Notre priorité</div><div><strong class="block text-2xl text-white">Football</strong>Notre passion</div></div></div>
  <div class="relative"><div class="absolute -inset-8 rounded-full bg-orange-500/10 blur-3xl"></div><div class="relative rounded-[2rem] border border-white/10 bg-white/[.06] p-6 shadow-2xl"><p class="text-xs font-black uppercase tracking-[.25em] text-orange-400">Prochain rendez-vous</p>@if($nextMatch)<div class="mt-8 grid grid-cols-[1fr_auto_1fr] items-center gap-4 text-center"><strong class="text-xl sm:text-2xl">A.S ZINGA</strong><span class="rounded-full bg-orange-500 px-3 py-2 text-xs font-black">VS</span><strong class="text-xl sm:text-2xl">{{ $nextMatch->opponent_name }}</strong></div><div class="mt-8 rounded-2xl bg-black/25 p-5 text-center"><p class="font-bold">{{ $nextMatch->kickoff_at->format('d/m/Y • H:i') }}</p><p class="mt-1 text-sm text-zinc-400">{{ $nextMatch->venue ?: 'Lieu à confirmer' }}</p></div>@else<div class="mt-7 rounded-2xl bg-black/25 p-7"><p class="text-xl font-black">Le prochain match arrive bientôt.</p><p class="mt-2 text-zinc-400">La programmation officielle sera affichée ici dès sa publication par le club.</p></div>@endif @if($lastMatch)<div class="mt-4 flex items-center justify-between rounded-2xl border border-white/10 p-4 text-sm"><span>Dernier résultat</span><strong>A.S ZINGA {{ $lastMatch->as_zinga_score }} — {{ $lastMatch->opponent_score }} {{ $lastMatch->opponent_name }}</strong></div>@endif</div></div>
 </div>
</section>

<section class="bg-white"><div class="mx-auto max-w-7xl px-4 py-20 lg:px-8"><div class="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p class="text-sm font-black uppercase tracking-[.2em] text-orange-600">Notre identité</p><h2 class="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Former, progresser, représenter.</h2></div><div class="text-lg leading-8 text-zinc-600"><p>A.S ZINGA est une association sportive implantée à Abobo. Le club veut offrir aux jeunes un cadre où le talent rencontre l’encadrement, où la passion devient discipline et où l’ambition se construit collectivement.</p><a href="{{ route('club') }}" class="mt-5 inline-flex font-black text-zinc-950">Découvrir l’histoire et le projet du club →</a></div></div><div class="mt-12 grid gap-4 md:grid-cols-3"><div class="rounded-3xl bg-zinc-950 p-7 text-white"><span class="text-3xl">⚽</span><h3 class="mt-5 text-xl font-black">Formation</h3><p class="mt-2 text-sm leading-6 text-zinc-400">Faire progresser les qualités techniques, tactiques et physiques de chaque joueur.</p></div><div class="rounded-3xl bg-orange-500 p-7"><span class="text-3xl">◆</span><h3 class="mt-5 text-xl font-black">Discipline</h3><p class="mt-2 text-sm leading-6 text-orange-950/80">Apprendre le respect, l’effort, la ponctualité et la responsabilité à travers le sport.</p></div><div class="rounded-3xl bg-zinc-100 p-7"><span class="text-3xl">↗</span><h3 class="mt-5 text-xl font-black">Ambition</h3><p class="mt-2 text-sm leading-6 text-zinc-600">Créer des opportunités et permettre aux talents de viser plus haut.</p></div></div></div></section>

<section class="bg-zinc-100"><div class="mx-auto max-w-7xl px-4 py-20 lg:px-8"><div class="grid gap-10 lg:grid-cols-2"><div class="rounded-[2rem] bg-orange-500 p-8 sm:p-12"><p class="text-sm font-black uppercase tracking-[.2em]">Le mot du président</p><blockquote class="mt-7 text-3xl font-black leading-tight sm:text-4xl">« Notre ambition est de donner à nos jeunes un cadre sérieux pour apprendre, grandir et croire en leur potentiel. »</blockquote><p class="mt-7 leading-7 text-orange-950/80">À A.S ZINGA, le résultat sportif compte, mais notre responsabilité va plus loin. Nous voulons bâtir un club respecté, proche de sa communauté et capable d’accompagner durablement les talents d’Abobo.</p><p class="mt-8 font-black">La Présidence<br><span class="font-medium text-orange-950/70">Association Sportive Zinga</span></p></div><div class="rounded-[2rem] bg-zinc-950 p-8 text-white sm:p-12"><p class="text-sm font-black uppercase tracking-[.2em] text-orange-400">Notre vision</p><h2 class="mt-5 text-4xl font-black">Faire du football un moteur d’avenir.</h2><p class="mt-5 leading-7 text-zinc-400">Le club veut créer une passerelle entre pratique sportive, éducation, valeurs humaines et opportunités. Chaque jeune doit pouvoir trouver ici un espace pour progresser et être considéré.</p><div class="mt-9 grid grid-cols-2 gap-3 text-sm"><div class="rounded-2xl border border-white/10 p-4"><strong class="block text-orange-400">01</strong><span class="mt-2 block font-bold">Respect</span></div><div class="rounded-2xl border border-white/10 p-4"><strong class="block text-orange-400">02</strong><span class="mt-2 block font-bold">Travail</span></div><div class="rounded-2xl border border-white/10 p-4"><strong class="block text-orange-400">03</strong><span class="mt-2 block font-bold">Solidarité</span></div><div class="rounded-2xl border border-white/10 p-4"><strong class="block text-orange-400">04</strong><span class="mt-2 block font-bold">Excellence</span></div></div></div></div></div></section>

@if($players->isNotEmpty())<section class="bg-white"><div class="mx-auto max-w-7xl px-4 py-20 lg:px-8"><div class="flex items-end justify-between gap-6"><div><p class="text-sm font-black uppercase tracking-[.2em] text-orange-600">L’effectif</p><h2 class="mt-2 text-4xl font-black">Nos joueurs</h2></div><a href="{{ route('team') }}" class="font-black">Voir l’équipe →</a></div><div class="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">@foreach($players as $player)<article class="overflow-hidden rounded-3xl bg-zinc-100">@if($player->photo_path)<img src="{{ asset('storage/'.$player->photo_path) }}" alt="{{ $player->display_name ?: $player->first_name.' '.$player->last_name }}" class="aspect-[4/5] w-full object-cover">@else<div class="grid aspect-[4/5] place-items-center bg-zinc-200 text-5xl font-black text-zinc-300">ASZ</div>@endif<div class="p-5"><p class="text-xs font-black uppercase tracking-wider text-orange-600">{{ $player->position }}</p><h3 class="mt-1 text-xl font-black">{{ $player->display_name ?: $player->first_name.' '.$player->last_name }}</h3></div></article>@endforeach</div></div></section>@endif

<section class="bg-zinc-950 text-white"><div class="mx-auto max-w-7xl px-4 py-20 lg:px-8"><div class="flex items-end justify-between gap-6"><div><p class="text-sm font-black uppercase tracking-[.2em] text-orange-400">Dans la vie du club</p><h2 class="mt-2 text-4xl font-black">Dernières actualités</h2></div><a href="{{ route('news.index') }}" class="font-black text-orange-400">Toutes les actualités →</a></div>@if($news->isEmpty())<div class="mt-9 rounded-3xl border border-dashed border-white/20 p-10 text-zinc-400">Les premières actualités du club seront bientôt publiées.</div>@else<div class="mt-9 grid gap-5 md:grid-cols-3">@foreach($news as $post)<article class="rounded-3xl border border-white/10 bg-white/[.05] p-7"><p class="text-xs font-black uppercase tracking-wider text-orange-400">{{ $post->published_at->format('d/m/Y') }}</p><h3 class="mt-3 text-2xl font-black">{{ $post->title }}</h3><p class="mt-4 leading-7 text-zinc-400">{{ $post->excerpt }}</p></article>@endforeach</div>@endif</div></section>

<section class="bg-orange-500"><div class="mx-auto max-w-7xl px-4 py-20 lg:px-8"><div class="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><p class="text-sm font-black uppercase tracking-[.2em]">Détection & recrutement</p><h2 class="mt-3 max-w-3xl text-4xl font-black tracking-tight sm:text-6xl">Ton histoire avec A.S ZINGA peut commencer ici.</h2><p class="mt-5 max-w-2xl text-lg text-orange-950/80">Tu es joueur et tu souhaites rejoindre le projet ? Présente ton profil directement au club.</p></div><a href="{{ route('recruitment') }}" class="inline-flex justify-center rounded-full bg-zinc-950 px-8 py-4 font-black text-white">Déposer ma candidature →</a></div></div></section>
@endsection
