@extends('layouts.app')
@section('content')
<section class="bg-zinc-950 text-white">
 <div class="mx-auto grid min-h-[620px] max-w-7xl items-center gap-10 px-4 py-16 lg:grid-cols-2 lg:px-8">
  <div><span class="inline-flex rounded-full border border-orange-400/40 bg-orange-500/10 px-3 py-1 text-sm font-bold text-orange-400">ABOBO • ABIDJAN</span><h1 class="mt-6 text-5xl font-black tracking-tight sm:text-7xl">A.S <span class="text-orange-500">ZINGA</span></h1><p class="mt-5 max-w-xl text-lg text-zinc-300">La passion du football, l'avenir de nos jeunes. Découvrez le club, nos joueurs, nos matchs et toute l'actualité de l'Association Sportive Zinga.</p><div class="mt-8 flex flex-wrap gap-3"><a href="{{ route('matches') }}" class="rounded-full bg-orange-500 px-6 py-3 font-bold">Voir nos matchs</a><a href="{{ route('team') }}" class="rounded-full border border-white/25 px-6 py-3 font-bold">Découvrir l'équipe</a></div></div>
  <div class="rounded-3xl border border-white/10 bg-white/5 p-6"><p class="text-xs font-black uppercase tracking-[.2em] text-orange-400">Prochain match</p>@if($nextMatch)<div class="mt-6 flex items-center justify-between gap-4 text-center"><div><strong class="text-2xl">A.S ZINGA</strong></div><span class="text-zinc-500">VS</span><div><strong class="text-2xl">{{ $nextMatch->opponent_name }}</strong></div></div><p class="mt-6 text-center text-zinc-300">{{ $nextMatch->kickoff_at->format('d/m/Y • H:i') }} @if($nextMatch->venue) • {{ $nextMatch->venue }} @endif</p>@else<p class="mt-5 text-zinc-300">Le prochain match sera annoncé ici dès sa programmation.</p>@endif</div>
 </div>
</section>
<section class="mx-auto max-w-7xl px-4 py-14 lg:px-8"><div class="flex items-end justify-between"><div><p class="text-sm font-black uppercase tracking-wider text-orange-600">Le club</p><h2 class="mt-2 text-3xl font-black">Dernières actualités</h2></div><a href="{{ route('news.index') }}" class="text-sm font-bold">Tout voir →</a></div>@if($news->isEmpty())<div class="mt-8 rounded-2xl border border-dashed border-zinc-300 p-8 text-zinc-500">Les premières actualités du club seront bientôt publiées.</div>@else<div class="mt-8 grid gap-5 md:grid-cols-3">@foreach($news as $post)<article class="rounded-2xl bg-white p-5 shadow-sm"><p class="text-xs font-bold text-orange-600">{{ $post->published_at->format('d/m/Y') }}</p><h3 class="mt-2 text-xl font-black">{{ $post->title }}</h3><p class="mt-3 text-sm text-zinc-600">{{ $post->excerpt }}</p></article>@endforeach</div>@endif</section>
<section class="bg-orange-500"><div class="mx-auto max-w-7xl px-4 py-12 text-center lg:px-8"><h2 class="text-3xl font-black">Tu veux rejoindre A.S ZINGA ?</h2><p class="mx-auto mt-3 max-w-2xl">Joueur, jeune talent, partenaire ou supporter : entre en contact avec le club.</p><a href="{{ route('contact') }}" class="mt-6 inline-flex rounded-full bg-zinc-950 px-6 py-3 font-bold text-white">Nous contacter</a></div></section>
@endsection
