@extends('layouts.app')
@section('title','Recrutement & Détection — A.S ZINGA')
@section('content')
<section class="mx-auto max-w-4xl px-4 py-14 lg:px-8"><p class="font-black uppercase tracking-widest text-orange-600">Rejoindre A.S ZINGA</p><h1 class="mt-2 text-4xl font-black">Recrutement & Détection</h1><p class="mt-3 max-w-2xl text-zinc-600">Présentez votre profil au club. L’envoi du formulaire ne garantit pas une sélection : chaque candidature est étudiée par l’encadrement.</p>
@if(session('success'))<div class="mt-6 rounded-xl bg-emerald-50 p-4 font-semibold text-emerald-800">{{ session('success') }}</div>@endif
@if($errors->any())<div class="mt-6 rounded-xl bg-red-50 p-4 text-red-700">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('recruitment.store') }}" class="mt-8 rounded-2xl bg-white p-5 shadow-sm sm:p-7">@csrf
<div class="grid gap-5 sm:grid-cols-2"><label class="text-sm font-bold">Nom complet<input required name="full_name" value="{{ old('full_name') }}" class="mt-2 w-full rounded-xl border border-zinc-300 px-4 py-3 font-normal"></label><label class="text-sm font-bold">Date de naissance<input required type="date" name="birth_date" value="{{ old('birth_date') }}" class="mt-2 w-full rounded-xl border border-zinc-300 px-4 py-3 font-normal"></label><label class="text-sm font-bold">Téléphone<input required name="phone" value="{{ old('phone') }}" class="mt-2 w-full rounded-xl border border-zinc-300 px-4 py-3 font-normal"></label><label class="text-sm font-bold">Email<input type="email" name="email" value="{{ old('email') }}" class="mt-2 w-full rounded-xl border border-zinc-300 px-4 py-3 font-normal"></label><label class="text-sm font-bold">Poste<input name="position" value="{{ old('position') }}" class="mt-2 w-full rounded-xl border border-zinc-300 px-4 py-3 font-normal"></label><label class="text-sm font-bold">Club actuel<input name="current_club" value="{{ old('current_club') }}" class="mt-2 w-full rounded-xl border border-zinc-300 px-4 py-3 font-normal"></label><label class="text-sm font-bold sm:col-span-2">Ville / quartier<input name="city" value="{{ old('city') }}" class="mt-2 w-full rounded-xl border border-zinc-300 px-4 py-3 font-normal"></label></div><label class="mt-5 block text-sm font-bold">Message<textarea name="message" rows="5" class="mt-2 w-full rounded-xl border border-zinc-300 px-4 py-3 font-normal">{{ old('message') }}</textarea></label><button class="mt-6 rounded-xl bg-orange-500 px-6 py-3 font-black text-white">Envoyer ma candidature</button></form></section>
@endsection
