@extends('layouts.app')
@section('title','Classement — A.S ZINGA')
@section('content')
<section class="relative overflow-hidden bg-zinc-950 text-white"><div class="absolute right-0 top-0 h-80 w-80 rounded-full bg-orange-500/20 blur-3xl"></div><div class="relative mx-auto max-w-7xl px-4 py-20 lg:px-8 lg:py-28"><p class="text-sm font-black uppercase tracking-[.22em] text-orange-400">Compétitions</p><h1 class="mt-4 text-5xl font-black tracking-tight sm:text-7xl">Classement <span class="text-orange-500">officiel.</span></h1><p class="mt-6 max-w-2xl text-lg leading-8 text-zinc-400">Les tableaux ci-dessous affichent uniquement les données enregistrées et validées par l’administration A.S ZINGA.</p></div></section>
<section class="bg-zinc-100"><div class="mx-auto max-w-7xl px-4 py-16 lg:px-8 lg:py-20">
 @forelse($competitions as $competition)
 <article class="mb-8 overflow-hidden rounded-[1.75rem] bg-white shadow-sm">
  <header class="flex flex-col gap-2 border-b border-zinc-200 p-6 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-black uppercase tracking-[.18em] text-orange-600">Compétition</p><h2 class="mt-1 text-3xl font-black">{{ $competition->name }}</h2></div>@if($competition->season)<span class="font-bold text-zinc-500">Saison {{ $competition->season }}</span>@endif</header>
  @if($competition->description)<p class="px-6 pt-5 text-sm leading-7 text-zinc-600">{{ $competition->description }}</p>@endif
  @if($competition->standings->isNotEmpty())
  <div class="overflow-x-auto p-4 sm:p-6"><table class="w-full min-w-[760px] text-sm"><thead><tr class="border-b border-zinc-200 text-left text-xs uppercase tracking-wider text-zinc-500"><th class="px-3 py-3">#</th><th class="px-3 py-3">Équipe</th><th class="px-3 py-3 text-center">MJ</th><th class="px-3 py-3 text-center">G</th><th class="px-3 py-3 text-center">N</th><th class="px-3 py-3 text-center">P</th><th class="px-3 py-3 text-center">BP</th><th class="px-3 py-3 text-center">BC</th><th class="px-3 py-3 text-center">Diff</th><th class="px-3 py-3 text-center">Pts</th></tr></thead><tbody>@foreach($competition->standings as $standing)<tr class="border-b border-zinc-100 {{ strcasecmp(trim($standing->team_name),'A.S ZINGA') === 0 ? 'bg-orange-50' : '' }}"><td class="px-3 py-4 font-black">{{ $standing->position }}</td><td class="px-3 py-4 font-black {{ strcasecmp(trim($standing->team_name),'A.S ZINGA') === 0 ? 'text-orange-600' : 'text-zinc-900' }}">{{ $standing->team_name }}</td><td class="px-3 py-4 text-center">{{ $standing->played }}</td><td class="px-3 py-4 text-center">{{ $standing->won }}</td><td class="px-3 py-4 text-center">{{ $standing->drawn }}</td><td class="px-3 py-4 text-center">{{ $standing->lost }}</td><td class="px-3 py-4 text-center">{{ $standing->goals_for }}</td><td class="px-3 py-4 text-center">{{ $standing->goals_against }}</td><td class="px-3 py-4 text-center">{{ $standing->goal_difference > 0 ? '+' : '' }}{{ $standing->goal_difference }}</td><td class="px-3 py-4 text-center text-lg font-black">{{ $standing->points }}</td></tr>@endforeach</tbody></table></div>
  @else<div class="p-10 text-center text-zinc-500">Le classement de cette compétition n’a pas encore été renseigné.</div>@endif
 </article>
 @empty<div class="rounded-[2rem] border border-dashed border-zinc-300 bg-white p-12 text-center"><strong class="text-xl">Aucune compétition publiée.</strong><p class="mt-2 text-zinc-500">Aucun classement fictif n’est affiché. Les compétitions apparaîtront ici après leur enregistrement officiel.</p></div>@endforelse
</div></section>
@endsection
