@extends('layouts.admin')
@section('title',$competition->exists ? 'Gérer la compétition' : 'Nouvelle compétition')
@section('content')
<div class="mb-6"><a href="{{ route('admin.competitions.index') }}" class="text-sm font-bold text-orange-600">← Compétitions</a><h1 class="mt-2 text-3xl font-black">{{ $competition->exists ? $competition->name : 'Nouvelle compétition' }}</h1></div>
<form method="POST" action="{{ $competition->exists ? route('admin.competitions.update',$competition) : route('admin.competitions.store') }}" class="rounded-2xl bg-white p-6 shadow-sm">@csrf @if($competition->exists) @method('PUT') @endif
 <div class="grid gap-5 md:grid-cols-2"><label class="font-bold">Nom<input name="name" value="{{ old('name',$competition->name) }}" required class="mt-2 w-full rounded-xl border-zinc-300"></label><label class="font-bold">Saison<input name="season" value="{{ old('season',$competition->season) }}" placeholder="2026-2027" class="mt-2 w-full rounded-xl border-zinc-300"></label><label class="font-bold">Ordre<input type="number" min="0" name="sort_order" value="{{ old('sort_order',$competition->sort_order ?? 0) }}" class="mt-2 w-full rounded-xl border-zinc-300"></label><label class="flex items-center gap-3 pt-8 font-bold"><input type="checkbox" name="is_active" value="1" {{ old('is_active',$competition->exists ? $competition->is_active : true) ? 'checked' : '' }}> Publier cette compétition</label></div>
 <label class="mt-5 block font-bold">Description<textarea name="description" rows="4" class="mt-2 w-full rounded-xl border-zinc-300">{{ old('description',$competition->description) }}</textarea></label>
 @if($errors->any())<div class="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{{ $errors->first() }}</div>@endif
 <button class="mt-6 rounded-xl bg-orange-500 px-6 py-3 font-black text-white">Enregistrer</button>
</form>
@if($competition->exists)<section class="mt-8 rounded-2xl bg-white p-6 shadow-sm"><div class="flex flex-wrap items-center justify-between gap-4"><div><p class="text-sm font-black uppercase tracking-widest text-orange-600">Classement</p><h2 class="text-2xl font-black">Équipes enregistrées</h2></div><a href="{{ route('admin.competitions.standings.create',$competition) }}" class="rounded-xl bg-zinc-950 px-5 py-3 font-black text-white">Ajouter une équipe</a></div><div class="mt-6 overflow-x-auto"><table class="w-full min-w-[720px] text-sm"><thead><tr class="border-b text-left text-zinc-500"><th class="p-3">#</th><th class="p-3">Équipe</th><th class="p-3">MJ</th><th class="p-3">G</th><th class="p-3">N</th><th class="p-3">P</th><th class="p-3">Pts</th><th class="p-3"></th></tr></thead><tbody>@forelse($competition->standings as $standing)<tr class="border-b border-zinc-100"><td class="p-3 font-black">{{ $standing->position }}</td><td class="p-3 font-bold">{{ $standing->team_name }}</td><td class="p-3">{{ $standing->played }}</td><td class="p-3">{{ $standing->won }}</td><td class="p-3">{{ $standing->drawn }}</td><td class="p-3">{{ $standing->lost }}</td><td class="p-3 font-black">{{ $standing->points }}</td><td class="p-3"><div class="flex gap-2"><a href="{{ route('admin.competitions.standings.edit',[$competition,$standing]) }}" class="font-bold text-orange-600">Modifier</a><form method="POST" action="{{ route('admin.competitions.standings.destroy',[$competition,$standing]) }}">@csrf @method('DELETE')<button class="font-bold text-red-600">Supprimer</button></form></div></td></tr>@empty<tr><td colspan="8" class="p-8 text-center text-zinc-500">Aucune équipe enregistrée dans ce classement.</td></tr>@endforelse</tbody></table></div></section>@endif
@endsection
