@extends('layouts.admin')
@section('title',$post->exists?'Modifier actualité':'Nouvelle actualité')
@section('content')
<h1 class="text-3xl font-black">{{ $post->exists?'Modifier l’actualité':'Nouvelle actualité' }}</h1>
<form method="POST" enctype="multipart/form-data" action="{{ $post->exists?route('admin.news.update',$post):route('admin.news.store') }}" class="mt-6 max-w-3xl space-y-5 rounded-2xl bg-white p-6">@csrf @if($post->exists)@method('PUT')@endif
@if($errors->any())<div class="rounded-xl bg-red-50 p-4 text-red-700">{{ $errors->first() }}</div>@endif
<label class="block font-bold">Titre<input required name="title" value="{{ old('title',$post->title) }}" class="mt-2 w-full rounded-xl border px-4 py-3 font-normal"></label>
<label class="block font-bold">Résumé<textarea name="excerpt" rows="3" class="mt-2 w-full rounded-xl border px-4 py-3 font-normal">{{ old('excerpt',$post->excerpt) }}</textarea></label>
<div class="rounded-2xl border border-zinc-200 p-5"><label class="block font-bold">Photo de couverture<input type="file" name="cover_image" accept="image/jpeg,image/png,image/webp" class="mt-2 block w-full text-sm font-normal"></label><p class="mt-2 text-xs text-zinc-500">JPG, PNG ou WebP — maximum 5 Mo.</p>@if($post->cover_image_path)<img src="{{ asset('storage/'.$post->cover_image_path) }}" alt="Couverture actuelle" class="mt-4 h-44 w-full rounded-xl object-cover"><label class="mt-3 flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="remove_cover" value="1"> Supprimer la photo actuelle</label>@endif</div>
<label class="block font-bold">Contenu<textarea required name="body" rows="10" class="mt-2 w-full rounded-xl border px-4 py-3 font-normal">{{ old('body',$post->body) }}</textarea></label><div class="grid gap-5 sm:grid-cols-2"><label class="font-bold">Statut<select name="status" class="mt-2 w-full rounded-xl border px-4 py-3 font-normal"><option value="draft" @selected(old('status',$post->status)==='draft')>Brouillon</option><option value="published" @selected(old('status',$post->status)==='published')>Publiée</option></select></label><label class="font-bold">Publication<input type="datetime-local" name="published_at" value="{{ old('published_at',$post->published_at?->format('Y-m-d\TH:i')) }}" class="mt-2 w-full rounded-xl border px-4 py-3 font-normal"></label></div><button class="rounded-xl bg-orange-500 px-5 py-3 font-black text-white">Enregistrer</button></form>
@endsection